Add auto_resolve field to group_trigger module to enable auto_resolve
dkorn/hawkular-alerts-module pull request #16
Opened 2017-02-23 15:48 UTC by zgalor

Add the auto_resolve field in the module and example playbook.

@dkorn @cben PTAL

2017-02-23 16:13 UTC, cben commented
Naive question: how does this relate to AUTORESOLVE trigger mode on conditions?

2017-02-23 16:45 UTC, zgalor commented
you can set it on the condition, but if you don't enable it on the trigger it wouldn't work.
IIUC the auto_resolve field of the trigger determines the alert state:
will it fire on every new metric that satisfies the condition, or will it fire once, and then enter auto-resolving state until a resolving metric arrives.

2017-02-26 09:47 UTC, dkorn reviewed
@zgalor Thanks for the contribution!

Please consider adding also:
* `auto_resolve_alerts` - Resolve all unresolved alerts when auto-resolve condition-set is satisfied
* `auto_resolve_match` - The policy used for deciding whether the trigger auto-resolved condition-set is satisfied. ALL conditions must evaluate to true or ANY one condition must evaluate to true.

Both are needed and can be part of this PR.

2017-02-26 09:47 UTC, dkorn commented on library/hawkular_alerts_group_trigger.py
> +      - is auto-resolve enabled
I'd add/change: "`, meaning switch to auto-resolve mode after firing"`

2017-02-26 09:58 UTC, zgalor commented
@dkorn I suggest we add those in a different PR, just for the sake of time. 
I will not get to it before Wednesday, and we should at least have the auto-resolve feature merged.

2017-03-02 08:06 UTC, zgalor commented
@cben @dkorn new fields added to allow collection in manageIQ - please review

2017-03-02 11:31 UTC, dkorn requested changes
Few minor comments and suggestions

2017-03-02 11:31 UTC, dkorn commented on library/hawkular_alerts_group_member.py
> +    required: False
Can you specify that a tag is a [name, value] pair? (like in the trigger module)

Please add `default: null`

2017-03-02 11:31 UTC, dkorn commented on library/hawkular_alerts_group_member.py
> +            tags=dict(required=False, type='dict'),
Looking at the Hawkular Alerts docs [1], it looks like `memberDescription` and `memberTags` are required (as well as `memberContext`).
It might be a recent change, otherwise, I'm not sure how this worked.

[1] http://www.hawkular.org/docs/rest/rest-alerts.html#GroupMemberInfo

2017-03-02 11:31 UTC, dkorn commented on library/hawkular_alerts_group_member.py
> +    member_description = module.params['description']
I would drop the `member` prefix from both `member_description` and `member_tags`
(I know it `member_name` has this prefix as well, also unneeded)

2017-03-02 11:31 UTC, dkorn commented on library/hawkular_alerts_group_trigger.py
> +        res_args = hawkular_alerts.create_or_update_group_trigger(name, event_text, group_id, severity, auto_resolve, tags, enabled, conditions)
please move `event_text` after `group_id`, as the latter is required.

2017-03-02 11:31 UTC, dkorn commented on library/hawkular_alerts_group_trigger.py
> +        if (event_text is not None and trigger.event_text != event_text):
As this grows (and will continue to) I think we should pass a dictionary of fields and iterate over them. something like:
```python
for attribute in group_trigger_attributes:
    if (attribute is not None and getattr(trigger, attribute) != attribute):
        updates[attribute] = attribute

```
@cben what do you think?

2017-03-02 13:12 UTC, zgalor commented on library/hawkular_alerts_group_member.py
> +            tags=dict(required=False, type='dict'),
yes, i spoke with @lucasponce. He said it's only a documentation error, and he will fix it.

2017-03-05 14:22 UTC, zgalor commented
@dkorn made the changes you requested and retested. Please review

2017-03-06 08:34 UTC, cben commented on library/hawkular_alerts_group_trigger.py
> +        if (event_text is not None and trigger.event_text != event_text):
Agree :+1:.

2017-03-06 08:43 UTC, cben commented on library/hawkular_alerts_group_trigger.py
> +                Empty Hash (None) - If the name, event_text, severity, auto_resolve, tags and enabled status passed
what does "Empty Hash (None)" mean?  `{} != None`.  Just say "Empty Hash".

I'd also stop listing here (twice) all the attributes compared, just say that all values match.

2017-03-07 08:25 UTC, zgalor commented
@dkorn @cben I applied your recommendation and generalized `required_updates` to loop through dictionary instead of specific `if`s.

Tested locally

2017-03-07 11:37 UTC, dkorn approved these changes

2017-03-07 11:46 UTC, dkorn approved these changes

2017-03-07 11:46 UTC, dkorn commented on library/hawkular_alerts_group_trigger.py
> +                                             "enabled": enabled})
I'd probaby change the dict creation to:

```python
dict([(i, locals()[i]) for i in ('name', group_id', auto_resolve', 'event_text', 'severity', 'enabled', 'tags')])
```
or
```python
attrs_to_compare = dict()
for i in ('name', group_id', auto_resolve', 'event_text', 'severity', 'enabled', 'tags'):
    attrs_to_compare[i] = locals()[i]
```

not a blocker

2017-03-07 11:46 UTC, merged